---
# tasks file for prod
- name: install packages
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - default-jdk
    - tomcat8
  
- name: Copy .war-file
  synchronize:
    src: /home/hello-1.0.war
    dest: /var/lib/tomcat8/webapps/
  notify:
    - restart tomcat
